readme.md

1. 写了一些comment，如果有不够好的，请修改
2. 修改了 Grass GIS

写了一些comment，如果有不够好的，请修改

---

readme.md

change GIS Clound to ---> GISCloud

fix for the wrong spell

---

readme.md

[jVectorMap](http://jvectormap.com/) is a vector-based, cross-browser and cross-platform component for interactive geography-related data visualization on the web.

Add jVectorMap

---

readme.md

`Technical Preview` to `Quartz Beta`.

Update ArcGIS Runtime SDK for Xamarin version

---

readme.md

I appended it to the iOS section.

Updated readme.md with mapbox iOS SDK

---

readme.md

Fixed a typo in mapbox ios skd -> sdk as well.

Added mapbox android sdk

---

Geospatial-Start-ups-And-Companies.md

GISbiz, Inc. sells custom applications development, GIS/IT consulting, and a mobile data application called geoOrganizer.

Add GISbiz, Inc.

---

readme.md

[Geo Maps](https://github.com/simonepri/geo-maps) is a project born with the purpose to programmatically extract maps from open databases like [OpenStreetMap](openstreetmap.org) providing you with a ready to use GeoJSON map that fits your needs.
The repo currently holds **3 type** of maps each exported in 13 different resolutions (from **1m** to **10km**), for a total of **39 maps** downloadable. All maps are also published as [npm packages](https://www.npmjs.com/org/geo-maps) to be used within nodeJS apps.
* [Geo Maps](https://github.com/simonepri/geo-maps)
* [Map of countries' political maritime boundaries](https://github.com/simonepri/geo-maps#maritime-boundaries)
* [Map of countries' political coastline boundaries](https://github.com/simonepri/geo-maps#maritime-coastline)
* [Map of …

Add geo-maps

---

Geospatial-Start-ups-And-Companies.md

[Mapzen is shutting down](https://mapzen.com/blog/shutdown/).

Remove mapzen

---

readme.md

[mapzen is shutting down by the end of the month](https://mapzen.com/blog/shutdown/).

Remove mapzen from readme

---

README.md

(Same codebase as desktop version, but different UI)

Add OpenOrienteering Mapper to Android section

---

README.md

I hope you find this resource suitable for your list. I am the author of this library.

Add d3-geomap

---

README.md

Large-scale WebGL-powered Geospatial Data Visualization By Ant Financial
https://github.com/antvis/L7

add L7  library

---

README.md

Add RoboSat.pink.
On RoboSat vs RoboSat.pink cf:
https://github.com/mapbox/robosat/issues/184
Latest RoboSat.pink presentations slides:
http://www.datapink.com/presentations/2019-sotm.pdf

Add RoboSat.pink

---

README.md

feat: add vue-mapbox

---

Geospatial-Start-ups-And-Companies.md

feat: add GeoSpoc GeoSpatial Services Private Ltd.

---

README.md

This is a repo inspired by an awesome structure but for reasons of usability I decided to evolve into a hybrid of wiki and awesome. So, it is a pretty big effort to compile hundred of resources for people brand new to ArcGIS in an easy to browse manner.

ArcGIS Awesome

---

Geospatial-Start-ups-And-Companies.md

Remove Redbird -> not existing anymore
Add Earthcube & Delair

Edit companies

---

README.md

Geopatra helps you create interactive maps with geopandas using the goodness of open source mapping libraries

Add geopatra

---

README.md

update mySQL->MySQL & remove invalid course & add GIS NJNU course

update mySQL->MySQL & remove invalid course & add GIS NJNU course

---

README.md

which helps you run GEE code and parse the result locally.
~.

add geemap package for Python&R.

---

README.md

add pydeck to python package list.
remove a space between rgee and its url to satisfy md format.

add pydeck to python package list.

---

README.md

Thanks for this awesome resources collection ;)

Added DEM Net Elevation API under 3D and C Sharp

---

README.md

https://eodag.readthedocs.io/en/latest/
Command line tool and a plugin-oriented Python framework for searching, aggregating results and downloading remote sensed images while offering a unified API for data access regardless of the data provider.

Add EODAG to the Python list

---

README.md

* WhirlyGlobe-Maply is an open source 3D globe and flat-map SDK for iOS and Android.
* It is stable, actively maintained, and has been used in production apps for years.
* Its large API supports fine-grained control over the map or globe, and it works with several GIS data formats.

Add WhirlyGlobe-Maply

---

README.md

I could not get the ordering of repos in JavaScript list.  Please adjust the order if required or let me know the same.

Added geojson2svg

---

README.md

MapD is now known as Omnisci. Description is still relevant.

Change MapD to Omnisci.

---

README.md

Suggesting the addition of Geosnap. Geosnap makes it easier to explore, model, analyze, and visualize the social and spatial dynamics of neighborhoods.

Add Geosnap - Python

---

README.md

Hi,
Stjepan from Manning here. I thought this title might be a good match for your list. Thank you for considering it.
Best,

Added PostGIS in Action, 3rd ed

---

README.md

Thanks for this awesome resources collection ;)

Added vue-cesium to  ths js list

---

README.md

I think `localtileserver` is pretty awesome 😎 , but I'm biased
If you think it's up to par, I'd love to see it join this list!
To learn more: https://github.com/banesullivan/localtileserver

🌐 Add localtileserver

---

README.md

Alphabetically sorted each list under each header in README.md, except for the Reference list. Furthermore, the Geospatial Library code headings were sorted alphabetically in the Table of Contents, as well as under the main Geospatial Library header in the body of the README.md file.

Sorted README.md lists in alphabetical order

---

README.md

Hi ! 
I suggest you Abc-Map. Disclaimer: I am the author of this software, but I think it will be useful.
Thanks for your useful list !
P.S.: not in alphabetical order because of the existing order.

Add abc-map

---

Geospatial-Start-ups-And-Companies.md

MapTiler is now a standalone company
OctoGEO ceased it`s activity

added MapTiler, removed OctoGEO

---

README.md

Adding changes to reflect the [ArcGIS Maps SDKs name change](https://www.esri.com/arcgis-blog/products/developers/announcements/introducing-the-arcgis-maps-sdks/) and some additional resources

Updating ArcGIS/Esri resources

---

README.md

Added new historical map awesome list

---

README.md

Hey, thanks for the awesome list!
Just wanted to include our recent Laravel package for PostGIS.
https://github.com/clickbar/laravel-magellan
Thanks!

readme: Include Laravel Magellan

---

README.md

Also fix some markdown syntax.

Add `orb` and `Golang-Ellipsoid`.

---

README.md

added Equator Studios to cloud SaaS section

Added Equator Studios to cloud SaaS section

---

README.md

Add QGis Awesome

---

README.md

http://mapsk.in redirects to https://1xbet1.in, "1xBet India Online Sport Betting & Casino Official Website"

Remove mapskin item
